### ISSUE TITLE
Support custom arbitrary values for color

### ISSUE THREAD

**Issue by retr00exe** [Devzstudio/tailwind_to_css#16]
Can we support arbitrary values for background color, border color, etc? My custom  `border-[#727272]` value is not showing
![image](https://user-images.githubusercontent.com/55347344/201590230-ffdbc184-5dd2-41b3-8d24-8b911442dd2d.png)

Best Regards,

**Comment by sboerrigter** [comment]
Some other custom values are also not working. Like `max-w-[180px]` and `aspect-[4/3]`.

![Screenshot 2023-05-11 at 09 40 25](https://github.com/Devzstudio/tailwind_to_css/assets/786875/1b1a7f91-163b-4512-8d3a-159083df0670)

**Comment by PJijin** [comment]
border color, aspect ratio, width and max width arbitrary values are supported now.
