### ISSUE TITLE
Add license & update all dependencies

### ISSUE THREAD

**Issue by staaph** [Devzstudio/tailwind_to_css#2]
Hi,

would you be open to add an Open Source license for the project? 
Here is a list https://api.github.com/licenses
I always tend to MIT.
Second question => should we update the dependencies? i got a vulnerability in node-fetch. 
I already tried a complete update with 
`ncu -u` command and it seemed to work well. Would have to check closer.

Best regards

**Comment by PJijin** [comment]
Hey 👋🏻,

Updated license. 
If needed you can update the dependencies. Feel free to make a pull request. 

Thank you

**Comment by staaph** [comment]
Alright,
I'm working on the responsiveness & updates.
