### ISSUE TITLE
missing convert Button after pasting tailwind code

### ISSUE THREAD

**Issue by uuc110** [Devzstudio/tailwind_to_css#21]
When I paste the code in the editior. the button Covert and whole nav bar get missing

![image](https://user-images.githubusercontent.com/44457947/217752398-368c0d7f-8738-428c-858f-85093b4e7a7d.png)

**Comment by 6vz** [comment]
any updates?

**Comment by PJijin** [comment]
Hey 

Currently, the tool is only capable of converting a specific part of the code. You should only paste the className portion for it to work correctly.
