### ISSUE TITLE
Doesn't seem to support breakpoint:class

### ISSUE THREAD

**Issue by georgiosd** [Devzstudio/tailwind_to_css#22]
Thank you guys for this tool 🙏 

These rules seem to fail until I remove the `breakpoint:` part.

e.g.
```
mx-auto grid max-w-2xl grid-cols-1 lg:mx-0 lg:max-w-none lg:grid-cols-2
```

**Comment by PJijin** [comment]
Hey @georgiosd 

I have implemented a temporary solution. The JSS code responsible for generating the style is experiencing problems with the breakpoint.

**Comment by georgiosd** [comment]
Thank you @PJijin !
