### ISSUE TITLE
Typing "[" crashes application

### ISSUE THREAD

**Issue by Ochidi** [Devzstudio/tailwind_to_css#27]
Typing the open square bracket character ("[") crashes the application with the following message: "Application error: a client-side exception has occurred (see the browser console for more information)."

This is what appears in the console:
![image](https://github.com/Devzstudio/tailwind_to_css/assets/3349058/8d32917f-e427-4e05-95b2-ab2768bc7d47)

It looks like while typing an arbitrary class for a tailwind style, it looks for a match inside the brackets that isn't there yet.

https://github.com/Devzstudio/tailwind_to_css/blob/ac124ec4df82993eac4d21d42d7cf95cfda1b715/libs/helpers.ts#LL52C6-L52C6

**Comment by xoptimal** [comment]
Can it be solved? Can it handle cases like [30px] and include them?  @PJijin

**Comment by PJijin** [comment]
@xoptimal Fixed issue with arbitrary values.
